version: '3.8'

services:
  # Neo4j Database
  neo4j:
    image: neo4j:5.13.0
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/sammy_swipe_secret
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
    networks:
      - sammy_net

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=sammy_swipe_secret
      - JWT_SECRET_KEY=your_secure_jwt_key_here
      - MODEL_PATH=/app/ml/models
    volumes:
      - ./ml/models:/app/ml/models
    depends_on:
      - neo4j
    networks:
      - sammy_net

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    networks:
      - sammy_net

  # ML Training Service
  ml_training:
    build:
      context: .
      dockerfile: Dockerfile.ml
    volumes:
      - ./ml/models:/app/models
      - ./ml/data:/app/data
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=sammy_swipe_secret
    depends_on:
      - neo4j
    networks:
      - sammy_net

networks:
  sammy_net:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import: 